
# Syntax highlighting
markdown:            kramdown
highlighter:         rouge


# Files excluded from Jekyll builds
exclude:
- README.md
- humans.txt
- jekyll-serve.sh
- install-ruby-gem.sh
- install-jekyll.sh
- .git

plugins:
  - github-pages
  - jekyll-feed

# Permalinks
permalink:           /:title.html


# Setup
timezone:            BST
locale:              en_gb
name:		     ' NIALL OBYRNES'
title:               'NIALL OBYRNES'
tagline:             ' '
description:         ''
url:                 http://niallobyrnes.github.io/
rss:
baseurl:             '/niallobyrnes.github.io'
baseurl_posts_img:   '/assets/img/posts/'
baseurl_featured_img: '/assets/img/hero/'
baseurl_featured_thumbnail: '/assets/img/thumbnail/'
baseurl_javascripts: '/assets/js/'
icon:                '/assets/img/icon.png' #[best 300px X 300px]
disqus:               # get it on https://disqus.com/admin/

author:
  name:           	 Niall Obyrnes
  url:            	 http://niallobyrnes.github.io
  facebook:          username
  twitter:           username
  google_plus:       username
  linkedin:          username
  dribbble:          username
  pinterest:         username
  github:            username
  bitbucket:         username

fb_admins:           your facebook profile id
fb_appid:            your facebook app id

# Server
destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port:             	 9001

defaults:

    -
      scope:
        path: "contact"
        type: "pages"
      values:
        layout: "default"

    -
      scope:
        path: "blog"
        type: "pages"
      values:
        layout: "default"

  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

  -
    scope:
      path: "/blog/_posts"
      type: "posts"
    values:
      layout: "default"
